package net.origamiking.mcmods.oem.datagen;

import net.fabricmc.fabric.api.blockrenderlayer.v1.BlockRenderLayerMap;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootTableProvider;
import net.fabricmc.fabric.api.datagen.v1.provider.SimpleFabricLootTableProvider;
import net.minecraft.client.render.RenderLayer;
import net.minecraft.data.server.loottable.BlockLootTableGenerator;
import net.minecraft.loot.LootTable;
import net.minecraft.loot.context.LootContextType;
import net.minecraft.util.Identifier;
import net.origamiking.mcmods.oem.OemMain;
import net.origamiking.mcmods.oem.blocks.ModBlocks;
import net.origamiking.mcmods.oem.blocks.concrete.ModBlocksConcreteSlabs;
import net.origamiking.mcmods.oem.blocks.concrete.ModBlocksConcreteStairs;
import net.origamiking.mcmods.oem.blocks.glass.ModBlocksGlass;
import net.origamiking.mcmods.oem.blocks.sculk.ModBlocksSculk;
import net.origamiking.mcmods.oem.blocks.server_specific.ModBlocksServerSpecific;
import net.origamiking.mcmods.oem.blocks.wood.barrel.ModBlocksBarrels;
import net.origamiking.mcmods.oem.blocks.wood.bookshelf.ModBlocksBookshelf;
import net.origamiking.mcmods.oem.blocks.wood.ladder.ModBlocksLadder;

import java.util.function.BiConsumer;

public class ModBlockLootTableGenerator extends FabricBlockLootTableProvider {
    public ModBlockLootTableGenerator(FabricDataOutput dataOutput) {
        super(dataOutput);
    }

    @Override
    public void generate() {
        addDrop(ModBlocksConcreteStairs.WHITE_CONCRETE_STAIR);
        addDrop(ModBlocksConcreteSlabs.WHITE_CONCRETE_SLAB);
        addDrop(ModBlocksConcreteStairs.LIGHT_GRAY_CONCRETE_STAIR);
        addDrop(ModBlocksConcreteSlabs.LIGHT_GRAY_CONCRETE_SLAB);
        addDrop(ModBlocksConcreteStairs.GRAY_CONCRETE_STAIR);
        addDrop(ModBlocksConcreteSlabs.GRAY_CONCRETE_SLAB);
        addDrop(ModBlocksConcreteStairs.BLACK_CONCRETE_STAIR);
        addDrop(ModBlocksConcreteSlabs.BLACK_CONCRETE_SLAB);
        addDrop(ModBlocksConcreteStairs.BROWN_CONCRETE_STAIR);
        addDrop(ModBlocksConcreteSlabs.BROWN_CONCRETE_SLAB);
        addDrop(ModBlocksConcreteStairs.RED_CONCRETE_STAIR);
        addDrop(ModBlocksConcreteSlabs.RED_CONCRETE_SLAB);
        addDrop(ModBlocksConcreteStairs.ORANGE_CONCRETE_STAIR);
        addDrop(ModBlocksConcreteSlabs.ORANGE_CONCRETE_SLAB);
        addDrop(ModBlocksConcreteStairs.YELLOW_CONCRETE_STAIR);
        addDrop(ModBlocksConcreteSlabs.YELLOW_CONCRETE_SLAB);
        addDrop(ModBlocksConcreteStairs.LIME_CONCRETE_STAIR);
        addDrop(ModBlocksConcreteSlabs.LIME_CONCRETE_SLAB);
        addDrop(ModBlocksConcreteStairs.GREEN_CONCRETE_STAIR);
        addDrop(ModBlocksConcreteSlabs.GREEN_CONCRETE_SLAB);
        addDrop(ModBlocksConcreteStairs.CYAN_CONCRETE_STAIR);
        addDrop(ModBlocksConcreteSlabs.CYAN_CONCRETE_SLAB);
        addDrop(ModBlocksConcreteStairs.LIGHT_BLUE_CONCRETE_STAIR);
        addDrop(ModBlocksConcreteSlabs.LIGHT_BLUE_CONCRETE_SLAB);
        addDrop(ModBlocksConcreteStairs.BLUE_CONCRETE_STAIR);
        addDrop(ModBlocksConcreteSlabs.BLUE_CONCRETE_SLAB);
        addDrop(ModBlocksConcreteStairs.PURPLE_CONCRETE_STAIR);
        addDrop(ModBlocksConcreteSlabs.PURPLE_CONCRETE_SLAB);
        addDrop(ModBlocksConcreteStairs.MAGENTA_CONCRETE_STAIR);
        addDrop(ModBlocksConcreteSlabs.MAGENTA_CONCRETE_SLAB);
        addDrop(ModBlocksConcreteStairs.PINK_CONCRETE_STAIR);
        addDrop(ModBlocksConcreteSlabs.PINK_CONCRETE_SLAB);
        addDrop(ModBlocksSculk.SCULK_STAIR);
        addDrop(ModBlocksSculk.SCULK_SLAB);
        addDrop(ModBlocksBarrels.OAK_BARREL);
        addDrop(ModBlocksLadder.OAK_LADDER);
        addDrop(ModBlocksBarrels.SPRUCE_BARREL);
        addDrop(ModBlocksLadder.SPRUCE_LADDER);
        addDrop(ModBlocksBookshelf.SPRUCE_BOOKSHELF);
        addDrop(ModBlocksLadder.BIRCH_LADDER);
        addDrop(ModBlocksBarrels.BIRCH_BARREL);
        addDrop(ModBlocksBookshelf.BIRCH_BOOKSHELF);
        addDrop(ModBlocksLadder.JUNGLE_LADDER);
        addDrop(ModBlocksBookshelf.JUNGLE_BOOKSHELF);
        addDrop(ModBlocksBarrels.JUNGLE_BARREL);
        addDrop(ModBlocksLadder.ACACIA_LADDER);
        addDrop(ModBlocksBookshelf.ACACIA_BOOKSHELF);
        addDrop(ModBlocksBarrels.ACACIA_BARREL);
        addDrop(ModBlocksLadder.DARK_OAK_LADDER);
        addDrop(ModBlocksBookshelf.DARK_OAK_BOOKSHELF);
        addDrop(ModBlocksBarrels.DARK_OAK_BARREL);
        addDrop(ModBlocksLadder.MANGROVE_LADDER);
        addDrop(ModBlocksBarrels.MANGROVE_BARREL);
        addDrop(ModBlocksBookshelf.MANGROVE_BOOKSHELF);
        addDrop(ModBlocksLadder.CRIMSON_LADDER);
        addDrop(ModBlocksBarrels.CRIMSON_BARREL);
        addDrop(ModBlocksBookshelf.CRIMSON_BOOKSHELF);
        addDrop(ModBlocksLadder.WARPED_LADDER);
        addDrop(ModBlocksBarrels.WARPED_BARREL);
        addDrop(ModBlocksBookshelf.WARPED_BOOKSHELF);
        addDrop(ModBlocksServerSpecific.GOLD_CHAIN);
        addDropWithSilkTouch(ModBlocksGlass.WHITE_GLASS_STAIR);
        addDropWithSilkTouch(ModBlocksGlass.WHITE_GLASS_SLAB);
        addDropWithSilkTouch(ModBlocksGlass.LIGHT_GRAY_GLASS_SLAB);
        addDropWithSilkTouch(ModBlocksGlass.LIGHT_GRAY_GLASS_STAIR);
        addDropWithSilkTouch(ModBlocksGlass.GRAY_GLASS_SLAB);
        addDropWithSilkTouch(ModBlocksGlass.GRAY_GLASS_STAIR);
        addDropWithSilkTouch(ModBlocksGlass.BLACK_GLASS_SLAB);
        addDropWithSilkTouch(ModBlocksGlass.BLACK_GLASS_STAIR);
        addDropWithSilkTouch(ModBlocksGlass.BROWN_GLASS_SLAB);
        addDropWithSilkTouch(ModBlocksGlass.BROWN_GLASS_STAIR);
        addDropWithSilkTouch(ModBlocksGlass.RED_GLASS_SLAB);
        addDropWithSilkTouch(ModBlocksGlass.RED_GLASS_STAIR);
        addDropWithSilkTouch(ModBlocksGlass.ORANGE_GLASS_SLAB);
        addDropWithSilkTouch(ModBlocksGlass.ORANGE_GLASS_STAIR);
        addDropWithSilkTouch(ModBlocksGlass.YELLOW_GLASS_SLAB);
        addDropWithSilkTouch(ModBlocksGlass.YELLOW_GLASS_STAIR);
        addDropWithSilkTouch(ModBlocksGlass.LIME_GLASS_SLAB);
        addDropWithSilkTouch(ModBlocksGlass.LIME_GLASS_STAIR);
        addDropWithSilkTouch(ModBlocksGlass.GREEN_GLASS_SLAB);
        addDropWithSilkTouch(ModBlocksGlass.GREEN_GLASS_STAIR);
        addDropWithSilkTouch(ModBlocksGlass.CYAN_GLASS_SLAB);
        addDropWithSilkTouch(ModBlocksGlass.CYAN_GLASS_STAIR);
        addDropWithSilkTouch(ModBlocksGlass.LIGHT_BLUE_GLASS_SLAB);
        addDropWithSilkTouch(ModBlocksGlass.LIGHT_BLUE_GLASS_STAIR);
        addDropWithSilkTouch(ModBlocksGlass.BLUE_GLASS_SLAB);
        addDropWithSilkTouch(ModBlocksGlass.BLUE_GLASS_STAIR);
        addDropWithSilkTouch(ModBlocksGlass.PURPLE_GLASS_SLAB);
        addDropWithSilkTouch(ModBlocksGlass.PURPLE_GLASS_STAIR);
        addDropWithSilkTouch(ModBlocksGlass.MAGENTA_GLASS_SLAB);
        addDropWithSilkTouch(ModBlocksGlass.MAGENTA_GLASS_STAIR);
        addDropWithSilkTouch(ModBlocksGlass.PINK_GLASS_SLAB);
        addDropWithSilkTouch(ModBlocksGlass.PINK_GLASS_STAIR);
        addDropWithSilkTouch(ModBlocksGlass.GLASS_SLAB);
        addDropWithSilkTouch(ModBlocksGlass.GLASS_STAIR);
        addDrop(ModBlocksServerSpecific.CAVERNS_BLOCK_ONE);
        addDrop(ModBlocksServerSpecific.CAVERNS_BLOCK_TWO);
        addDrop(ModBlocksServerSpecific.CAVERNS_BLOCK_THREE);
        addDrop(ModBlocksServerSpecific.CAVERNS_BLOCK_FOUR);
        addDrop(ModBlocksServerSpecific.CAVERNS_BLOCK_FIVE);
        addDrop(ModBlocksServerSpecific.CAVERNS_BLOCK_SIX);
        addDrop(ModBlocksServerSpecific.GOLD_LANTERN);

    }
}
